steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        cd fr-google-jukebox && docker build -t $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME .

  - id: push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME

  - id: deploy
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy $_SERVICE_NAME \
        --project $_AR_PROJECT_ID \
        --image $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME \
        --allow-unauthenticated \
        --set-env-vars=ENV=production,PROJECT_ID=$_AR_PROJECT_ID,GCLOUD_PROJECT_ID=$_AR_PROJECT_ID,GCLOUD_PROJECT_NUMBER=395380200712,GCLOUD_MUSIC_BUCKET=my-jukebox-app-prompts-results,FIRESTORE_DATABASE=my-jukebox-app \
        --update-secrets=GOOGLE_APP_EMAIL=GOOGLE_APP_EMAIL:latest,GOOGLE_APP_PASSWORD=GOOGLE_APP_PASSWORD:latest \
        --region $_DEPLOY_REGION \
        --timeout 3600 \
        --platform managed

images:
  - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME

options:
  logging: CLOUD_LOGGING_ONLY